runtime: nodejs20
env: flex
service: backend

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ''

env_variables:
  NODE_ENV: production
