openapi: 3.0.0
info:
  title:  IT Talent API - Analysis Module
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /analysis:
    get:
      tags:
      - Analysis
      summary: Get all analysis
      description: Retrieves a list of all analysis entries.
      responses:
        "200":
          description: A list of analysis entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Analysis"
    post:
      tags:
      - Analysis
      summary: Create or update an analysis entry
      description: Creates or update an analysis entry with the provided data.
      parameters:
        - in: body
          name: analysis
          required: true
          schema:
            $ref: "#/definitions/CreationAnalysisUser"
        - name: authorization
          in: header
          schema:
            type: string
            required: true
            description: Its the token of authentication.
      responses:
        "201":
          description: Analysis entry created successfully
          content:
            application/json:
              schema:
                $ref: "#/definitions/Analysis"
  /analysis/{id}:
    get:
      tags:
      - Analysis
      summary: Get an analysis entry by ID
      description: Retrieves an analysis entry by its unique identifier.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: The unique identifier for the analysis entry.
        - name: authorization
          in: header
          schema:
            type: string
            required: true
            description: Its the token of authentication(use to verify notifications).
      responses:
        "200":
          description: The analysis entry with the specified ID
          content:
            application/json:
              schema:
                $ref: "#/definitions/Analysis"
  /analysis/github/{username}:
    get:
      tags:
      - Analysis
      summary: Get an analysis entry by ID
      description: Retrieves an analysis entry by its unique identifier.
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          description: The username of the analysis you are looking for.
      responses:
        "200":
          description: The analysis entry with the specified ID
          content:
            application/json:
              schema:
                $ref: "#/definitions/Analysis"
   
    delete:
      patch:
      tags:
      - Analysis
      summary: Delete an analysis entry by the username
      description: Delete an existing analysis entry with the provided data.
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          description: The username that you are updating.
      responses:
        "204":
          description: Analysis entry deleted successfully
definitions:
  SearchForAnalysisUser:
    type: object
    required:
      - username
    properties:
      username:
        type: string
        description: The username that you are searching for.
  CreationAnalysisUser:
    type: object
    required:
      - username
    properties:
      username:
        type: string
        description: The GitHub username for which the analysis is being created.
      apikey:
        type: string
        description: Optional API key for authentication.
  Analysis:
    type: object
    required:
      - githubUsername
      - followers
      - avatarUrl
      - contributions
      - topLanguages
      - technologies
      - topRepositories
    properties:
      githubUsername:
        type: string
        description: The github username of the analysis.
      followers:
        type: integer
        description: The number of followers of this github user
      url:
        type: string
        format: uri
        description: The URL of the avatar of the github account.
      contributions:
        type: object
        description: The contributions of the github user
        properties:
          totalCommits:
            type: integer
            description: The actual total number of commits
          totalPullRequests:
            type: integer
            description: The actual total number of pull requests
      topLanguages:
        type: array
        description: The top languages more used by this github user.
        items:
          type: object
          properties:
            language:
              type: string
              description: The name of the language
            count:
              type: integer
              description: The total number of uses
      topRepositories:
        type: array
        description: The top recent repositories of the github user.
        items:
          type: object
          properties:
            name:
              type: string
              description: The name of the repository.
            url:
              type: string
              format: uri
              description: The URL of the repository.
            stars:
              type: integer
              description: The number of stars of the repository
            forks:
              type: integer
              description: The number of forks of the repository
            languages:
              type: array
              items:
                type: string
              description: The list of programming languages used in the repository.
            technologies:
              type: array
              items:
                type: string
              description: The list of technologies used in the repository.
