swagger: "3.0.0"
info:
  version: 1.0.0
  title: IT Talent API - History Module
paths:
  /history:
    get:
      tags:
        - Read All
      summary: Get history from user
      description: Get the complete history of a representative
      responses:
        200:
          description: ºSuccess
          schema:
            type: array
            items:
              $ref: "#/definitions/HistoryItem"
    post:
      tags:
        - Create
      summary: Create history entry
      description: Create a new entry in the history of a representative
      parameters:
        - name: body
          in: body
          description: History entry object
          required: true
          schema:
            $ref: "#/definitions/HistoryItem"
      responses:
        201:
          description: Created
  /history/{id}:
      get:
        tags:
          - Read
        summary: Get history entry by ID
        description: Get a specific history entry by its ID
        parameters:
          - name: id
            in: path
            description: ID of the history entry
            required: true
            type: string
        responses:
          200:
            description: Success
            schema:
              $ref: "#/definitions/HistoryItem"
      patch:
        tags:
          - Update
        summary: Update history entry
        description: Update a specific history entry
        parameters:
          - name: id
            in: path
            description: ID of the history entry
            required: true
            type: string
          - name: body
            in: body
            description: History entry object
            required: true
            schema:
              $ref: "#/definitions/HistoryItem"
        responses:
          200:
            description: Success
      delete:
        tags:
          - Delete
        summary: Delete history entry
        description: Delete a specific history entry
        parameters:
          - name: id
            in: path
            description: ID of the history entry
            required: true
            type: string
          - name: authorization
            in: header
            schema:
              type: string
              required: true
              description: Its the token of authentication.
        responses:
          204:
            description: No content
  /history/favorites:
    patch:
        tags:
          - Update
        summary: Update 
        description: Update a specific history entry
        parameters:
          - name: id
            in: path
            description: ID of the history entry
            required: true
            type: string
          - name: body
            in: body
            description: History entry object
            required: true
            schema:
              $ref: "#/definitions/HistoryItem"
        responses:
          200:
            description: Success
definitions:
  HistoryItem:
    type: object
    properties:
      id:
        type: string
        format: uuiid
        required: true
        description: The unique identifier for the history item.
      date:
        type: date
        required: true
        description: The acquisition date the history item.
      favorite:
        type: boolean
        required: true
        description: The state of the history item