openapi: 3.0.0
info:
  title:  IT Talent API - Analysis Module
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /user/notification:
    get:
      tags:
        - Notification
      summary: Get all notifications
      description: Get all the notifications of the db
      responses:
        200:
          description: ºSuccess
          schema:
            type: array
            items:
              $ref: "#/definitions/NotificationItem"
  /user/{userId}/notification:
    get:
      tags:
        - Notification
      summary: Get the mailbox of a candidate
      description: Get the mailbox of a candidate
      parameters:
      - name: userId
        in: path
        description: ID of the user
        required: true
        type: string
      - name: authorization
        in: header
        schema:
          type: string
          required: true
          description: Its the token of authentication.
      responses:
        200:
          description: ºSuccess
          schema:
            type: array
            items:
              $ref: "#/definitions/NotificationItem"
   
definitions:
  NotificationItem:
    type: object
    properties:
      candidateId:
        type: string
        format: uuiud
        required: true
        description: The unique ID of the candidate
      representativeId:
        type: string
        format: uuiud
        required: true
        description: The unique ID of the representative
      date:
        type: string
        required: true
        description: The notification date.
      message:
        type: string
        required: true
        description: The message of the notification.