#!/bin/sh

log_error() {
    printf "Error: %s\n" "$1" >&2
    exit 1
}

if [ ! -d ".git" ]; then
    log_error "This script must be run at the root of a Git repository."
fi

recursive_js_cleanup() {
    find . -type f -name '*.js' -delete &
}

current_dir=$(pwd)

echo "Cleaning Frontend folder on $current_dir/app"
cd app/ || log_error "Unable to change directory to 'app/'"

rm -rf node_modules
rm -rf dist
echo "Cleaning Frontend folder on $current_dir/app Success"

cd "$current_dir" || log_error "Unable to change back to the original directory"

echo "Cleaning Backend versions on $current_dir/api"
cd api/ || log_error "Unable to change directory to 'api/'"

for folder in v[0-9]*; do
    cd "$folder" || continue
    echo "Version $folder cleaning"
    rm -rf node_modules
    recursive_js_cleanup
    echo "Version $folder cleaning Success"
    cd ..
done

