  name: Generate a new release following Semantic Versioning

  on:
    push:
      branches: [develop]
    pull_request:
      branches: [main]

  jobs:
    ### Include test execution for future tests.
    release:
      runs-on: ubuntu-latest
      needs: test

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Use Node.js 20.8.1
          uses: actions/setup-node@v4
          with:
            node-version: '20.8.1'

        - name: Install dependencies
          run: npm install

        - name: Semantic Release
          run: npx semantic-release 