name: Generate a new release following Semantic Versioning

on:
  push:
    branches: [main, develop]

jobs:
  ### Include test execution for future tests.
  release:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Use Node.js 20.8.1
          uses: actions/setup-node@v4
          with:
            node-version: '20.8.1'

        - name: Set up environment variables
          run: |
            echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

        - name: Install dependencies
          run: npm install

        - name: Semantic Release
          run: npx semantic-release 
          